baseurl = "https://cortosconto.netlify.com/"  # Include trailing slash
title = "Cortosconto"
theme = "newsroom"
author = "Weru"
copyright = "Copyright &copy; 2020, Cortosconto and the Hugo Authors; all rights reserved."
canonifyurls = true
paginate = 3
# Enable syntax highlighting
# comment or delete lines 11 ~ 14
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

# Alternatively, you can use chroma instead of pigments
# to do so comment or delete lines 11 ~ 14 and uncomment lines 17 ~ 27
# [markup]
#   [markup.highlight]
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineNoStart = 1
#     lineNos = true
#     lineNumbersInTable = true
#     noClasses = false
#     # style = "monokai"
#     tabWidth = 2

disqusShortname = "cortosconto"

[params]
  ga_analytics = "UA-112361799-5"  
  twitter = "@pio_zingaro"

